# Generated by Django 6.0.5 on 2026-06-16 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_packer", "0009_seed_kubernetes_cloud_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packertemplate",
            name="zabbix_server",
            field=models.CharField(
                blank=True,
                default="zabbix.nmulti.cloud",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "Enter a valid Zabbix server address. Allowed: hostname or IP "
                            "(optionally with :port), multiple entries comma-separated. No "
                            "spaces or shell metacharacters."
                        ),
                        regex="^[A-Za-z0-9.\\-\\[\\]]+(:[0-9]{1,5})?(,[A-Za-z0-9.\\-\\[\\]]+(:[0-9]{1,5})?)*$",
                    )
                ],
            ),
        ),
    ]
