# Generated by Django 6.0.5 on 2026-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_packer", "0017_update_fileserver_agent_package_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packertemplate",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
